project 'Cura.xcodeproj'

# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'Cura' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for Cura
    pod 'IQKeyboardManagerSwift'
    pod 'UICircularProgressRing'
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'Localize-Swift', '~> 2.0'
    pod 'Alamofire', '~> 4.5'
    pod 'AlamofireImage', '~> 3.3'
    pod 'AlertOnboarding'
    pod 'SwiftyJSON'
    pod 'SCLAlertView', :git => 'https://github.com/maxim-danilov-anoda/SCLAlertView-Swift'
end
